---
- name: getrepo
  get_url:
      url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      dest: /home/vagrant
      owner: root
      group: root

- name: rpm epel install
  yum:
     name: /home/vagrant/epel-release-latest-7.noarch.rpm
     state: present

- name: install server
  yum:
    name: "{{ web }}"  
    state: installed
