---
- hosts: prod
  become: yes
  vars:
    web: nginx
  tasks:
    - name: updating system
      yum:
        name: '*'
        state: installed
    - name: nginx install 
      yum:
        name: "{{web}}"
        state: installed
    - name: nginx service start
      service:
        name: "{{web}}"
        state: started
        enabled: yes 

